name = "PushRecovery"
uuid = "e5d7e63e-020d-11e9-1e2d-c1b17e981caa"
authors = ["Twan Koolen <koolen.twan@gmail.com>"]
version = "0.1.0"

[deps]
AtlasRobot = "436ed74b-f7b6-57fe-bd82-efdbd6c0ab0c"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
NamedColors = "51fcb6bd-ecd8-522c-95bc-4099d1d03463"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Parametron = "41fac6d6-0ffa-5bcc-b863-17dd4947be41"
PlanarConvexHulls = "145d500b-351c-58b3-a0aa-f5d7e249d989"
QPControl = "d1d18edd-2826-5709-814b-0b0c7d0d034b"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RigidBodySim = "e61f16d8-a6b7-5689-8d03-627c2b27ebce"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticUnivariatePolynomials = "6f584044-cad5-5b68-a429-1e244a824f76"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["NBInclude", "Pkg", "Test", "UnicodePlots", "ForwardDiff"]

